name: pokemon_api_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  get_it: ^6.1.1
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/pokeball-svg.svg

  fonts:
    - family: Pokemon-Solid
      fonts:
        - asset: assets/fonts/Pokemon-Solid.ttf
    - family: Pokemon-Hollow
      fonts:
        - asset: assets/fonts/Pokemon-Hollow.ttf
